### ISSUE TITLE
EP-Launch Lite on MacOS for 8.4.0 references 8.3.0 for weather and fails

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5415]
EP-Launch Lite that was distributed with EnergyPlus 8.4.0 Update 1 when run generates an error shown below:

![eplaunchliteerror1](https://cloud.githubusercontent.com/assets/2582150/12299395/27d599a0-b9dc-11e5-932f-ed744fec4f4b.PNG)

Then the main screen shows the version being 8.3 and does not populate the weather file pull down list

![eplaunchliteerror2](https://cloud.githubusercontent.com/assets/2582150/12299425/469e7064-b9dc-11e5-90a0-607a1b70d87f.PNG)

Then files do not run because the weather file is missing and there is no way to select any of them. In addition the script that is run has a note at the top that the script is deprecated as of August 2015 and the CLI should be used instead. The script should probably not be marked that way since it is still being used by EP-Launch Lite.

**Comment by JasonGlazer** [comment]
@kbenne @mbadams5 @Myoldmopar I thought you would want to see this.

**Comment by JasonGlazer** [comment]
See:

https://unmethours.com/question/2392/energyplus-simulation-on-mac-os/

**Comment by RKStrand** [comment]
Similar issues noted in Issue #5427 except a crash did not happen but bad references are made

**Comment by mastercodekw** [comment]
Did anyone find a solution for this problem ?

**Comment by JasonGlazer** [comment]
@alsarraf I do not believe this has been addressed yet.

**Comment by ncardwel** [comment]
Posted an [issue](https://unmethours.com/question/18301/install-problem-with-energyplus-840-update-1/) on Unmethours and was led here.  I'm still seeing this issue with v8.5 with OSX.

**Comment by rustymyers** [comment]
Found this issue in testing our 8-5-0 deployments today. It was closed as duplicate: https://github.com/NREL/EnergyPlusBuildSupport/issues/30

**Comment by Myoldmopar** [comment]
Closed via #5867
