### ISSUE TITLE
Confusing sizing output for fan coil unit

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7276]
Issue overview
--------------
Autosized fan coil unit results in this error:
```
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water LGSTORE1 ZN COOLING COIL
   **   ~~~   ** User-Specified Design Air Flow Rate [m3/s] = 0.79234
   **   ~~~   ** differs from Design Size Design Air Flow Rate [m3/s] = 0.87231
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
```

From @rraustad helpesk response and notes:
I seems you are doing nothing wrong with your inputs. I ran this file in the debugger and see that the input for design air vol flow rate is read in as "autosize". The fan coil then writes a value to that input to set the air flow rate. Then the coil sizes and thinks that input was hard-sized since it now has a value. So this is an issue with the E+ engine, not your inputs. Simply disregard this for now until we can figure out how to move forward.

Interesting, coil 11, LGstore1 ZN Cooling Coil, reads in -99999 as DesAirVolFlowRate in GetInput but by the time the sizing routine is called, it's 0.79234 ???? It's getting set somewhere, just need to find it.

In FanCoilUnits, this sets the size of coil 11 before that coil has sized. FinalZoneSizng.DesCoolVolFlow = 0.79234 here.

```
if (ZoneSizingRunDone) {
SetCoilDesFlow(CoolingCoilType, CoolingCoilName, FinalZoneSizing(CurZoneEqNum).DesCoolVolFlow, ErrorsFound);
SetCoilDesFlow(FanCoil(FanCoilNum).HCoilType, FanCoil(FanCoilNum).HCoilName, FinalZoneSizing(CurZoneEqNum).DesHeatVolFlow, ErrorsFound);
```

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.1+?
 - Unmethours [37236](https://unmethours.com/question/37236/where-user-specified-value-disagrees-with-autosizing/) and helpdesk ticket 13182

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached 
[Strip Mall sizing conflict.zip](https://github.com/NREL/EnergyPlus/files/3098406/Strip.Mall.sizing.conflict.zip)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Regardless of the fact that the fan coil and other zone equipment override air flow rates for child water coil components, why does the fan coil set a cooling flow rate for the cooling coil and heating flow for the heating coil when the fan coil has only 1 operating air flow rate?

    ZoneHVAC:FourPipeFanCoil,
      LGstore1 ZN Fan Coil,    !- Name
      FanAvailSched,           !- Availability Schedule Name
      CyclingFan,              !- Capacity Control Method
      autosize,                !- Maximum Supply Air Flow Rate {m3/s}

These lines commented out:

        if (ZoneSizingRunDone) {
            SetCoilDesFlow(CoolingCoilType, CoolingCoilName, FinalZoneSizing(CurZoneEqNum).DesCoolVolFlow, ErrorsFound);
            SetCoilDesFlow(FanCoil(FanCoilNum).HCoilType, FanCoil(FanCoilNum).HCoilName, FinalZoneSizing(CurZoneEqNum).DesHeatVolFlow, ErrorsFound);
        } else {
            SetCoilDesFlow(CoolingCoilType, CoolingCoilName, FanCoil(FanCoilNum).MaxAirVolFlow, ErrorsFound);
            SetCoilDesFlow(FanCoil(FanCoilNum).HCoilType, FanCoil(FanCoilNum).HCoilName, FanCoil(FanCoilNum).MaxAirVolFlow, ErrorsFound);
        }

The initial purpose of this function is as follows. The Coil:Cooling:Water:DetailedGeometry and Coil:Heating:Water are the only water coils without an air vol flow input field (also Coil:Heating:Steam) so maybe those coil types (and only those coil types) need to set air flow? Will need to check this.

        void SetCoilDesFlow()
        // PURPOSE OF THIS SUBROUTINE:
        // This routine is designed to set the design air volume flow rate in the
        // water coil data structure. Some of the coil types do not have this datum as
        // an input parameter and it is needed for calculating capacity for output reporting.

After commenting the above lines out, and letting the ZoneEqSizing data set at the bottom of the fan coil sizing routine do what is intended,

        if (CurZoneEqNum > 0) {
            ZoneEqSizing(CurZoneEqNum).MaxHWVolFlow = FanCoil(FanCoilNum).MaxHotWaterVolFlow;
            ZoneEqSizing(CurZoneEqNum).MaxCWVolFlow = FanCoil(FanCoilNum).MaxColdWaterVolFlow;
            ZoneEqSizing(CurZoneEqNum).AirVolFlow = FanCoil(FanCoilNum).MaxAirVolFlow;
            ZoneEqSizing(CurZoneEqNum).DesCoolingLoad = FanCoil(FanCoilNum).DesCoolingLoad;
            ZoneEqSizing(CurZoneEqNum).DesHeatingLoad = FanCoil(FanCoilNum).DesHeatingLoad;
        }

the sizing results seem correct. Except that the cooling coil air flow sizing is the max of cooling and heating air flow instead of the cooling air flow as implied by the commented code described above.

    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, LGSTORE1 ZN FAN COIL, Design Size Maximum Supply Air Flow Rate [m3/s], 0.87231
    Component Sizing Information, Fan:OnOff, LGSTORE1 ZN SUPPLY FAN, Design Size Maximum Flow Rate [m3/s], 0.87231
    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, LGSTORE1 ZN FAN COIL, Design Size Maximum Hot Water Flow [m3/s], 4.46918E-004
    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, LGSTORE1 ZN FAN COIL, Design Size Maximum Cold Water Flow [m3/s], 4.57622E-004
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Inlet Air Temperature [C], 23.97560
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Inlet Water Temperature [C], 7.22000
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Inlet Air Humidity Ratio, 9.29699E-003
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Outlet Air Temperature [C], 12.80000
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Outlet Air Humidity Ratio, 8.50000E-003
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Water Flow Rate [m3/s], 4.57622E-004
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Air Flow Rate [m3/s], 0.87231
    Component Sizing Information, Coil:Heating:Water, LGSTORE1 ZN HEATING COIL, Design Size Rated Capacity [W], 20228.24486
    Component Sizing Information, Coil:Heating:Water, LGSTORE1 ZN HEATING COIL, Design Size Maximum Water Flow Rate [m3/s], 4.46918E-004
    Component Sizing Information, Coil:Heating:Water, LGSTORE1 ZN HEATING COIL, Design Size U-Factor Times Area Value [W/K], 460.66240

The remaining question is why were the water coils singled out as a component that needed the parent object to control air flow sizing? Per the function comment, the SetCoilDesFlow function was created in 2009 so has been used for a very long time (good information no longer required in the new functions we create).

**Comment by rraustad** [comment]
It's interesting that the water cooling coil water flow rate was not affected by commenting out the call to SetCoilDesFlow. Results of original defect file (using a schedule value of 1 for missing schedule files) using V9.1 code base (i.e., call to SetCoilDesFlow in FanCoil sizing is not commented out).

    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, LGSTORE1 ZN FAN COIL, Design Size Maximum Supply Air Flow Rate [m3/s], 0.87231
    Component Sizing Information, Fan:OnOff, LGSTORE1 ZN SUPPLY FAN, Design Size Maximum Flow Rate [m3/s], 0.87231
    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, LGSTORE1 ZN FAN COIL, Design Size Maximum Hot Water Flow [m3/s], 4.46918E-004
    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, LGSTORE1 ZN FAN COIL, Design Size Maximum Cold Water Flow [m3/s], 4.57622E-004
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Inlet Air Temperature [C], 23.97560
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Inlet Water Temperature [C], 7.22000
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Inlet Air Humidity Ratio, 9.29699E-003
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Outlet Air Temperature [C], 12.80000
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Outlet Air Humidity Ratio, 8.50000E-003
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Water Flow Rate [m3/s], 4.57622E-004
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, Design Size Design Air Flow Rate [m3/s], 0.87231
    Component Sizing Information, Coil:Cooling:Water, LGSTORE1 ZN COOLING COIL, User-Specified Design Air Flow Rate [m3/s], 0.79234
    Component Sizing Information, Coil:Heating:Water, LGSTORE1 ZN HEATING COIL, Design Size Rated Capacity [W], 20228.24486
    Component Sizing Information, Coil:Heating:Water, LGSTORE1 ZN HEATING COIL, Design Size Maximum Water Flow Rate [m3/s], 4.46918E-004
    Component Sizing Information, Coil:Heating:Water, LGSTORE1 ZN HEATING COIL, Design Size U-Factor Times Area Value [W/K], 460.66240

**Comment by rraustad** [comment]
@mjwitte I suggest as a solution to remove the SetCoilDesFlow function and use ZoneEqSizing as the method to pass parent sizing info to child components? Any objections?

**Comment by rraustad** [comment]
Find all "SetCoilDesFlow", Match case, Subfolders, Find Results 1, Entire Solution, ""
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\FanCoilUnits.cc(1383):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\FanCoilUnits.cc(2108):        //    SetCoilDesFlow(CoolingCoilType, CoolingCoilName, FinalZoneSizing(CurZoneEqNum).DesCoolVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\FanCoilUnits.cc(2109):        //    SetCoilDesFlow(FanCoil(FanCoilNum).HCoilType, FanCoil(FanCoilNum).HCoilName, FinalZoneSizing(CurZoneEqNum).DesHeatVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\FanCoilUnits.cc(2111):        //    SetCoilDesFlow(CoolingCoilType, CoolingCoilName, FanCoil(FanCoilNum).MaxAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\FanCoilUnits.cc(2112):        //    SetCoilDesFlow(FanCoil(FanCoilNum).HCoilType, FanCoil(FanCoilNum).HCoilName, FanCoil(FanCoilNum).MaxAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\HVACSingleDuctInduc.cc(764):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\HVACSingleDuctInduc.cc(1065):                SetCoilDesFlow(IndUnit(IUNum).HCoilType, IndUnit(IUNum).HCoil, TermUnitSizing(CurTermUnitSizingNum).AirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\HVACSingleDuctInduc.cc(1068):                SetCoilDesFlow(IndUnit(IUNum).CCoilType, IndUnit(IUNum).CCoil, TermUnitSizing(CurTermUnitSizingNum).AirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\MixedAir.cc(4850):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\MixedAir.cc(4967):                    SetCoilDesFlow(CoilType, CoilName, this->MinOA, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\PackagedTerminalHeatPump.cc(4772):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\PackagedTerminalHeatPump.cc(5365):        SetCoilDesFlow(PTUnit(PTUnitNum).ACHeatCoilType, PTUnit(PTUnitNum).ACHeatCoilName, PTUnit(PTUnitNum).MaxHeatAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\PoweredInductionUnits.cc(989):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\PoweredInductionUnits.cc(1467):                SetCoilDesFlow(PIU(PIUNum).HCoilType, PIU(PIUNum).HCoil, TermUnitSizing(CurTermUnitSizingNum).AirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\SimAirServingZones.cc(3964):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\SimAirServingZones.cc(4047):                SetCoilDesFlow(CoilType, CoilName, PrimaryAirSystem(AirLoopNum).DesignVolFlowRate, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\SingleDuct.cc(2342):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\SingleDuct.cc(3096):                    SetCoilDesFlow(
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\SingleDuct.cc(3099):                    SetCoilDesFlow(Sys(SysNum).ReheatComp, Sys(SysNum).ReheatName, TermUnitSizing(CurTermUnitSizingNum).AirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\UnitarySystem.cc(714):                    WaterCoils::SetCoilDesFlow(DataHVACGlobals::cAllCoilTypes(this->m_HeatingCoilType_Num),
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\UnitarySystem.cc(789):                WaterCoils::SetCoilDesFlow(DataHVACGlobals::cAllCoilTypes(this->m_SuppHeatCoilType_Num),
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\UnitHeater.cc(978):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\UnitHeater.cc(1353):        SetCoilDesFlow(UnitHeat(UnitHeatNum).HCoilTypeCh, UnitHeat(UnitHeatNum).HCoilName, UnitHeat(UnitHeatNum).MaxAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\UnitVentilator.cc(1629):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\UnitVentilator.cc(2469):        SetCoilDesFlow(CoolingCoilType, CoolingCoilName, UnitVent(UnitVentNum).MaxAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\UnitVentilator.cc(2470):        SetCoilDesFlow(UnitVent(UnitVentNum).HCoilTypeCh, UnitVent(UnitVentNum).HCoilName, UnitVent(UnitVentNum).MaxAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\VentilatedSlab.cc(1752):        using WaterCoils::SetCoilDesFlow;
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\VentilatedSlab.cc(2406):        SetCoilDesFlow(CoolingCoilType, CoolingCoilName, VentSlab(Item).MaxAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\VentilatedSlab.cc(2407):        SetCoilDesFlow(VentSlab(Item).HCoilTypeCh, VentSlab(Item).HCoilName, VentSlab(Item).MaxAirVolFlow, ErrorsFound);
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\WaterCoils.cc(5841):    void SetCoilDesFlow(std::string const &CoilType, // must match coil types in this module
    C:\Users\Richard\Documents\GitHub\EnergyPlusTeam-Parallel\src\EnergyPlus\WaterCoils.hh(533):    void SetCoilDesFlow(std::string const &CoilType, // must match coil types in this module
    Matching lines: 31    Matching files: 13    Total files searched: 1468

**Comment by mjwitte** [comment]
>  I suggest as a solution to remove the SetCoilDesFlow function and use ZoneEqSizing as the method to pass parent sizing info to child components? Any objections?

What's the difference between these two options?

**Comment by rraustad** [comment]
SetCoilDesFlow sets the input for child coil air flow rate prior to sizing. For Coil:Cooling:Water this appears to the sizing routine as a user input. The other 2 coil types don't report air flow.
The ZoneEqSizing array is used to pass information to the child during sizing so as to appear to be the autosized result.

Pretty sure SetCoilDesFlow pre-dates use of ZoneEqSizing and so that new method never replaced SetCoilDesFlow.

   void SetCoilDesFlow (**used in parent objects prior to coil sizing**):

        if (UtilityRoutines::SameString(CoilType, "Coil:Heating:Water") ||
            UtilityRoutines::SameString(CoilType, "Coil:Cooling:Water:DetailedGeometry") ||
            UtilityRoutines::SameString(CoilType, "Coil:Cooling:Water")) {
            WhichCoil = UtilityRoutines::FindItem(CoilName, WaterCoil);
            if (WhichCoil != 0) {
                if (UtilityRoutines::SameString(CoilType, "Coil:Cooling:Water") && WaterCoil(WhichCoil).DesAirVolFlowRate < 0.0) {
                    WaterCoil(WhichCoil).DesAirVolFlowRate = CoilDesFlow;
                } else {
                    WaterCoil(WhichCoil).DesAirVolFlowRate = CoilDesFlow;
                }
            } else {
                ShowSevereError("GetCoilMaxWaterFlowRate: Could not find Coil, Type=\"" + CoilType + "\" Name=\"" + CoilName + "\"");
                ErrorsFound = true;
            }

**Comment by crollinjones** [comment]
I am reviewing a model with fan coils. I could not understand why the heating mass flow rate was very much lower than the cooling coil mass flow rate - 1% in one fan coil. The flows are too low to keep the spaces at heating setpoint. I was hoping there was a minimum flow rate input that would override the sized flow rate if less than that user specified minimum - 0.4 cfm/ft2. Where did that number come from?

**Comment by mjwitte** [comment]
@crollinjones Support questions like this should be directed to unmethours.com or the EnergyPlus helpdesk energyplus.helpserve.com or e-mail energy-support@gard.com with the idf attached.

**Comment by crollinjones** [comment]
Thank you @mjwitte.

**Comment by matthew-larson** [comment]
@rraustad @mjwitte In fixing an issue regarding the outputs for the cooling coils referenced in fan coil units, I realized the sizing discrepancy and created issue #7998 only to find out this issue also exists.  My issue came about when I was hard-sizing the air flow rate in the ZoneHVAC:FourPipeFanCoil object and letting the associated water coil autosize the air flow rate.  The sizing of the water coil was being based on the autosized air flow rate instead of the hard-sized air flow rate in the ZoneHVAC:FourPipeFanCoil object.  Since you've done some investigation with this issue, I wanted to make sure I don't overstep or conflict with this issue.  I had already created a pull request as well so you can see the changes.

**Comment by mjwitte** [comment]
@matthew-larson I thought we fixed that long long ago - forcing the parent flow rate onto the child coils and fan. The discussion on this issue implies that was working at some point. Or maybe it only worked in the fan coil flow was autosized? @rraustad ?

**Comment by matthew-larson** [comment]
@mjwitte @rraustad The SetCoilDesFlow function is still present in the code contrary to the suggestion.  I think my changes are basically doing what @rraustad suggested in terms of using the ZoneEqSizing to pass the airflow to the child components.
